package mcrcon

import (
    "github.com/chzyer/readline"
)

// newCommandCompleter creates an autocompleter for common Minecraft commands
func newCommandCompleter() *readline.PrefixCompleter {
	return readline.NewPrefixCompleter(
		readline.PcItem("help"),
		readline.PcItem("list"),
		readline.PcItem("say"),
		readline.PcItem("tell"),
		readline.PcItem("give"),
		readline.PcItem("tp"),
		readline.PcItem("teleport"),
		readline.PcItem("time",
			readline.PcItem("set",
				readline.PcItem("day"),
				readline.PcItem("night"),
				readline.PcItem("noon"),
				readline.PcItem("midnight"),
			),
			readline.PcItem("add"),
			readline.PcItem("query"),
		),
		readline.PcItem("weather",
			readline.PcItem("clear"),
			readline.PcItem("rain"),
			readline.PcItem("thunder"),
		),
		readline.PcItem("gamemode",
			readline.PcItem("survival"),
			readline.PcItem("creative"),
			readline.PcItem("adventure"),
			readline.PcItem("spectator"),
		),
		readline.PcItem("difficulty",
			readline.PcItem("peaceful"),
			readline.PcItem("easy"),
			readline.PcItem("normal"),
			readline.PcItem("hard"),
		),
		readline.PcItem("kill"),
		readline.PcItem("kick"),
		readline.PcItem("ban"),
		readline.PcItem("ban-ip"),
		readline.PcItem("pardon"),
		readline.PcItem("pardon-ip"),
		readline.PcItem("op"),
		readline.PcItem("deop"),
		readline.PcItem("whitelist",
			readline.PcItem("add"),
			readline.PcItem("remove"),
			readline.PcItem("list"),
			readline.PcItem("on"),
			readline.PcItem("off"),
			readline.PcItem("reload"),
		),
		readline.PcItem("save-all"),
		readline.PcItem("save-on"),
		readline.PcItem("save-off"),
		readline.PcItem("stop"),
		readline.PcItem("seed"),
		readline.PcItem("setblock"),
		readline.PcItem("fill"),
		readline.PcItem("clone"),
		readline.PcItem("gamerule"),
		readline.PcItem("setworldspawn"),
		readline.PcItem("defaultgamemode"),
	)
}
